/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode

import java.nio.file.Paths

fun main() {
    val currentDirectory = Paths.get("").toAbsolutePath().toString()
//    mainDay1(currentDirectory)
//    mainDay2(currentDirectory)
    mainDay3(currentDirectory)
}
